# Generated by Django 4.2.7 on 2023-11-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='kategoriID',
            field=models.IntegerField(default=255, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='berita',
            name='status',
            field=models.CharField(choices=[('publish', 'publish'), ('draft', 'draft')], default=255, max_length=200),
            preserve_default=False,
        ),
    ]
